### PR TITLE
Add phone-number-related methods

### PR DESCRIPTION
**Pull request by Chaewon382**
Added a few methods using users' phone numbers including 'add friends using phone number', 'disconnect friends using phone number' etc. For now, it is using temporary user repo, but it will be updated soon. 
Also, I made a few changes to FriendsListRepo by simply commenting out the previous code. Those comment blocks are going to be cleared out once all changes are approved by Jeonghoon.

### CODE REVIEW

**Comment by ramib20** [comment]
looks good, good job including comments with the code!

**Review by kimhajiny — APPROVED** [review]
Looks good to me!

**Review by hyunhee804 — COMMENTED** [review]
Looks very good to me too! Thanks for the clarification and clear codes!

**Review by jeonghoon6764 — COMMENTED** [review]
I think looking up the user from the phone number is inefficient.
We can try another algorithm or discuss it later. Great job!

**Pull request merged**
