### PR TITLE
add global token variable

### PR DESCRIPTION
**Pull request by hyunhee804**
added global token variable and you can use this variable to access token value that gets generated when you log in

### CODE REVIEW

**Review by Chaewon382 — APPROVED** [review]
Since this variable is going to be used accross multiple classes, token would better be a "public static" variable so that it can accessed via Utility.token

**Review by Chaewon382 — APPROVED** [review]
Reviewed the change! Thanks for reflecting the feedback.

**Comment by jeonghoon6764** [comment]
> Reviewed the change! Thanks for reflecting the feedback.

looks good thanks

**Review by jeonghoon6764 — APPROVED** [review]
Looks great thanks

**Review by taehee5525 — APPROVED** [review]

**Pull request merged**
