### PR TITLE
Backend feature friend repo

### PR DESCRIPTION
**Pull request by jeonghoon6764**
PR

Added repository interface to support friends list is uploaded.
Added repository class to support a friends list is added.

We will use JPA later, but now we will use a temporary repository that implements the interface.
Thanks.

### CODE REVIEW

**Review by hyunhee804 — COMMENTED** [review]
looks great

**Review by kimhajiny — APPROVED** [review]
Looks good!

**Review by Chaewon382 — APPROVED** [review]
Thanks for starting to work on friends feature. But I'm wondering if we could make the friends list as an attribute of User since it is part of user info. We can discuss this more later! Anyway, great work :)

**Comment by ramib20** [comment]
looks good, great work!

**Pull request merged**
